# Generated by Django 3.0.6 on 2020-06-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25, null=True)),
                ('lastnmae', models.CharField(max_length=10, null=True)),
                ('emailid', models.CharField(max_length=25, null=True)),
                ('password', models.CharField(max_length=12, null=True)),
                ('confirmpassword', models.CharField(max_length=12, null=True)),
            ],
        ),
    ]
